### ISSUE TITLE
Wareframe de novo design

### ISSUE THREAD

**Issue by pedrobonifacio** [jussimar/MeAjudaBaixadaApp#2]
Fiz um novo esboço que muda um pouco o conceito da forma do App.
Quando a pessoa entra ela vai ter la em cima o login, e dois botões de sobre e parceria, que vai abrir outras paginas.
​Na pagina de parceria o usuário poderá se cadastrar como parceiro, depois de logado terá um ícone de perfil ou a foto do usuário, na parte principal vai ter um scroll infinito com os pedidos de ajuda, vai ter só informações como nome (peguei essas informações no app, pode ser mudado), categoria e data. Quando clicar no pedido vai para uma pagina com mais detalhes e poderá aceitar ajudar aquele pedido, o botão help poderia trocar para um "+" ou outra coisa mais intuitivo, não coloquei cores porque é algo a se discutir.

![Protótipo](https://user-images.githubusercontent.com/50744385/85872304-ed7b7780-b7a5-11ea-9e6d-7609af2c9ad6.png)

**Comment by anabeatrizzz** [comment]
Ótimo esboço Pedro, mas pelo que foi explicado os parceiros serão instituições onde a doação será entregue. Então não tem necessidade deles fazerem login.

**Comment by pedrobonifacio** [comment]
Na página de parceiros terá a opção a opção "DESEJO SER PARCEIRO" que antes estava na tela inicial.
